import { AIChatBox } from "@/components/AIChatBox";
import { AppLoading, AuthError, StudentAppShell } from "@/components/StudentAppShell";
import { useSupabaseAuth } from "@/contexts/SupabaseAuthContext";
import { trpc } from "@/lib/trpc";
import { BotMessageSquare, Plus, RefreshCcw, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";

const learningModes = [
  ["teach", "Teach me"], ["explain", "Explain"], ["simplify", "Simplify"], ["examples", "Examples"],
  ["step_by_step", "Step-by-step"], ["practice", "Practice"], ["quiz_me", "Quiz me"], ["exam_prep", "Exam prep"],
] as const;

export default function Chat() {
  const { user, loading, authError } = useSupabaseAuth();
  const [, setLocation] = useLocation(); const utils = trpc.useUtils();
  const conversations = trpc.chat.list.useQuery(undefined, { enabled: Boolean(user) });
  const documents = trpc.documents.list.useQuery(undefined, { enabled: Boolean(user) });
  const [activeId, setActiveId] = useState<number | null>(null); const [mode, setMode] = useState<(typeof learningModes)[number][0]>("teach"); const [documentId, setDocumentId] = useState(""); const [pending, setPending] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const active = trpc.chat.get.useQuery({ conversationId: activeId ?? 0 }, { enabled: Boolean(activeId) });
  const create = trpc.chat.create.useMutation({ onSuccess: conversation => { utils.chat.list.invalidate(); setActiveId(conversation.id); } });
  const send = trpc.chat.send.useMutation({ onSuccess: () => { setPending(null); utils.chat.get.invalidate({ conversationId: activeId ?? 0 }); utils.chat.list.invalidate(); }, onError: caught => { setPending(null); setError(caught.message); } });
  const regenerate = trpc.chat.regenerate.useMutation({ onSuccess: () => { utils.chat.get.invalidate({ conversationId: activeId ?? 0 }); }, onError: caught => setError(caught.message) });
  useEffect(() => { if (!loading && !authError && !user) setLocation("/login"); }, [authError, loading, setLocation, user]);
  useEffect(() => { if (!activeId && conversations.data?.[0]) setActiveId(conversations.data[0].id); }, [activeId, conversations.data]);
  if (loading) return <AppLoading />; if (authError) return <AuthError message={authError} />; if (!user) return <AppLoading />;
  const displayMessages = [...(active.data?.messages ?? []), ...(pending ? [{ role: "user" as const, content: pending }] : [])];
  async function startConversation() { setError(null); try { const conversation = await create.mutateAsync({ learningMode: mode }); setActiveId(conversation.id); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not create a conversation."); } }
  async function sendMessage(content: string) { setError(null); let conversationId = activeId; try { if (!conversationId) { const conversation = await create.mutateAsync({ learningMode: mode }); conversationId = conversation.id; setActiveId(conversationId); } setPending(content); await send.mutateAsync({ conversationId, content, documentId: documentId ? Number(documentId) : undefined }); } catch (caught) { setPending(null); setError(caught instanceof Error ? caught.message : "Could not send your message."); } }
  return <StudentAppShell><div className="mx-auto flex min-h-screen max-w-[1400px] flex-col p-5 sm:p-8 lg:p-10"><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-[13px] font-medium text-[#724060]">Academic workspace</p><h1 className="mt-1 text-[30px] font-semibold tracking-[-.045em]">Study chat</h1><p className="mt-2 text-sm text-[#724060]">A private assistant that keeps your learning conversation in context.</p></div><div className="flex flex-wrap gap-2"><select value={mode} onChange={event => setMode(event.target.value as (typeof learningModes)[number][0])} className="h-10 rounded-xl border border-[#A070A1] bg-[#FDF3F3] px-3 text-[12px] font-medium text-[#724060] outline-none focus:border-[#A070A1]">{learningModes.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={documentId} onChange={event => setDocumentId(event.target.value)} className="h-10 max-w-[180px] rounded-xl border border-[#A070A1] bg-[#FDF3F3] px-3 text-[12px] font-medium text-[#724060] outline-none focus:border-[#A070A1]"><option value="">No document source</option>{documents.data?.map(document => <option key={document.id} value={document.id}>{document.originalName}</option>)}</select><button onClick={startConversation} disabled={create.isPending} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#724060] px-4 text-[13px] font-medium text-[#FDF3F3] hover:bg-[#724060]"><Plus className="h-4 w-4" />New chat</button></div></header>{error && <p role="alert" className="mt-5 rounded-xl bg-[#F8E7E7] p-3 text-[13px] text-[#A070A1]">{error}</p>}
    <div className="mt-7 grid min-h-[620px] flex-1 gap-4 lg:grid-cols-[270px_minmax(0,1fr)]"><aside className="rounded-2xl border border-[#A070A1] bg-[#FDF3F3] p-3"><p className="px-2 py-2 text-[11px] font-semibold uppercase tracking-[.12em] text-[#724060]">Conversations</p><div className="mt-1 space-y-1">{conversations.isLoading ? <p className="px-2 py-4 text-[13px] text-[#724060]">Loading…</p> : conversations.data?.length ? conversations.data.map(conversation => <button key={conversation.id} onClick={() => { setPending(null); setActiveId(conversation.id); }} className={`w-full rounded-xl px-3 py-3 text-left transition ${activeId === conversation.id ? "bg-[#F8E7E7] text-[#A070A1]" : "hover:bg-[#F8E7E7]"}`}><p className="truncate text-[13px] font-medium">{conversation.title}</p><p className="mt-1 text-[11px] text-[#724060]">{learningModes.find(([value]) => value === conversation.learningMode)?.[1] ?? conversation.learningMode}</p></button>) : <div className="px-3 py-8 text-center"><BotMessageSquare className="mx-auto h-5 w-5 text-[#A070A1]" /><p className="mt-3 text-[12px] leading-5 text-[#724060]">Your real study conversations will appear here.</p></div>}</div></aside>
      <section className="min-w-0"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-xl bg-[#F8E7E7] text-[#A070A1]"><Sparkles className="h-4 w-4" /></span><div><p className="text-[13px] font-semibold">{active.data?.conversation.title ?? "New study conversation"}</p><p className="text-[11px] text-[#724060]">Responses are saved to your account.</p></div></div>{active.data?.messages.some(message => message.role === "assistant") && <button onClick={() => activeId && regenerate.mutate({ conversationId: activeId })} disabled={regenerate.isPending || send.isPending} className="inline-flex h-8 items-center gap-1.5 rounded-lg px-2.5 text-[12px] font-medium text-[#A070A1] hover:bg-[#F8E7E7]"><RefreshCcw className={`h-3.5 w-3.5 ${regenerate.isPending ? "animate-spin" : ""}`} />Regenerate</button>}</div><AIChatBox messages={displayMessages} onSendMessage={sendMessage} isLoading={send.isPending || regenerate.isPending} height="calc(100vh - 260px)" placeholder="Ask about a concept, method, or practice question…" emptyStateMessage="Begin a focused study conversation" className="rounded-2xl border-[#A070A1] shadow-none" /></section></div>
  </div></StudentAppShell>;
}
