import { AppLoading, AuthError, StudentAppShell } from "@/components/StudentAppShell";
import { useSupabaseAuth } from "@/contexts/SupabaseAuthContext";
import { getSupabaseAccessToken } from "@/lib/supabase";
import { trpc } from "@/lib/trpc";
import { ExternalLink, FileText, LockKeyhole, UploadCloud } from "lucide-react";
import { ChangeEvent, useEffect, useState } from "react";
import { useLocation } from "wouter";

export default function Documents() {
  const { user, loading, authError } = useSupabaseAuth(); const [, setLocation] = useLocation(); const utils = trpc.useUtils();
  const documents = trpc.documents.list.useQuery(undefined, { enabled: Boolean(user) });
  const [uploading, setUploading] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { if (!loading && !authError && !user) setLocation("/login"); }, [authError, loading, setLocation, user]);
  if (loading) return <AppLoading />; if (authError) return <AuthError message={authError} />; if (!user) return <AppLoading />;
  async function handleUpload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; setError(null); setNotice(null); if (file.type !== "application/pdf") { setError("Choose a PDF file."); return; } if (file.size > 12 * 1024 * 1024) { setError("PDF files must be 12 MB or smaller."); return; } const token = getSupabaseAccessToken(); if (!token) { setError("Your session is no longer active. Please sign in again."); return; } setUploading(true); try { const response = await fetch("/api/documents/upload", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/pdf", "X-File-Name": encodeURIComponent(file.name) }, body: file }); const body = await response.json() as { error?: string; document?: { status: string; originalName: string } }; if (!response.ok) throw new Error(body.error || "Upload failed."); setNotice(body.document?.status === "ready" ? `${body.document.originalName} is ready for study.` : `${body.document?.originalName || "Your PDF"} was stored but could not be indexed.`); await utils.documents.list.invalidate(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not upload your PDF."); } finally { setUploading(false); } }
  return <StudentAppShell><div className="mx-auto max-w-[1200px] p-5 sm:p-8 lg:p-10"><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-[13px] font-medium text-[#724060]">Academic workspace</p><h1 className="mt-1 text-[30px] font-semibold tracking-[-.045em]">Documents</h1><p className="mt-2 text-sm text-[#724060]">Private source material, stored with user-scoped access controls.</p></div><label className={`inline-flex h-10 items-center gap-2 rounded-xl bg-[#724060] px-4 text-[13px] font-medium text-[#FDF3F3] ${uploading ? "cursor-wait opacity-70" : "cursor-pointer hover:bg-[#724060]"}`}><UploadCloud className="h-4 w-4" />{uploading ? "Processing PDF…" : "Upload PDF"}<input type="file" accept="application/pdf" onChange={handleUpload} disabled={uploading} className="sr-only" /></label></header>{error && <p role="alert" className="mt-5 rounded-xl bg-[#F8E7E7] p-3 text-[13px] text-[#A070A1]">{error}</p>}{notice && <p role="status" className="mt-5 rounded-xl bg-[#F8E7E7] p-3 text-[13px] text-[#A070A1]">{notice}</p>}
    <div className="mt-8 rounded-2xl border border-[#A070A1] bg-[#FDF3F3]"><div className="flex items-center gap-2 border-b border-[#A070A1] p-5"><LockKeyhole className="h-4 w-4 text-[#A070A1]" /><div><h2 className="text-[14px] font-semibold">Private document library</h2><p className="mt-1 text-[12px] text-[#724060]">Files are never exposed through public application URLs.</p></div></div>{documents.isLoading ? <div className="p-6 text-[13px] text-[#724060]">Loading documents…</div> : documents.data?.length ? <div className="divide-y divide-[#A070A1]">{documents.data.map(document => <div key={document.id} className="flex items-center gap-4 p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#F8E7E7] text-[#A070A1]"><FileText className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-medium">{document.originalName}</p><p className="mt-1 text-[11px] text-[#724060]">{Math.ceil(document.byteSize / 1024)} KB · {document.pageCount ? `${document.pageCount} pages` : "Indexed text"} · uploaded {new Date(document.createdAt).toLocaleDateString()}</p></div><a href={`/api/documents/${document.id}/download`} target="_blank" rel="noreferrer" className="inline-flex h-8 items-center gap-1 rounded-lg px-2.5 text-[12px] font-medium text-[#A070A1] hover:bg-[#F8E7E7]">Open <ExternalLink className="h-3.5 w-3.5" /></a></div>)}</div> : <div className="px-6 py-16 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#F8E7E7] text-[#A070A1]"><FileText className="h-5 w-5" /></span><h2 className="mt-5 text-[17px] font-semibold">Add private study material</h2><p className="mx-auto mt-2 max-w-sm text-[13px] leading-5 text-[#724060]">Upload a selectable-text PDF. StudentGPT extracts and indexes it within your own document space.</p></div>}</div>
  </div></StudentAppShell>;
}
