import { useSupabaseAuth } from "@/contexts/SupabaseAuthContext";
import { getSupabaseBrowserClient } from "@/lib/supabase";
import { isEmailConfirmationError } from "@/lib/authRecovery";
import { AppLoading } from "@/components/StudentAppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ArrowUpRight, LockKeyhole } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { useLocation, useSearch } from "wouter";

type View = "signIn" | "signUp" | "forgot" | "reset";

export default function Login() {
  const { user, loading, authError, signIn, signUp, requestPasswordReset, updatePassword } = useSupabaseAuth();
  const [, setLocation] = useLocation(); const search = useSearch();
  const [view, setView] = useState<View>(search.includes("reset=1") ? "reset" : "signIn");
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [fullName, setFullName] = useState("");
  const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false); const [needsConfirmation, setNeedsConfirmation] = useState(false);
  useEffect(() => { if (user) setLocation("/"); }, [setLocation, user]);
  if (loading) return <AppLoading />;

  async function handleSubmit(event: FormEvent) {
    event.preventDefault(); setError(null); setNotice(null); setNeedsConfirmation(false); setSubmitting(true);
    try {
      if (view === "signIn") { await signIn(email, password); setLocation("/"); }
      else if (view === "signUp") { if (password !== confirmPassword) throw new Error("Your passwords do not match."); const result = await signUp(email, password, fullName); if (result.emailConfirmationRequired) { setNotice("Check your email to confirm your account, then return here to sign in."); setView("signIn"); } else setLocation("/"); }
      else if (view === "forgot") { await requestPasswordReset(email); setNotice("If that address is registered, a password-reset link is on its way."); }
      else { await updatePassword(password); setNotice("Your password is updated. You can continue securely."); setView("signIn"); }
    } catch (caught) { const message = caught instanceof Error ? caught.message : "We could not complete that request."; if (isEmailConfirmationError(message)) { setNeedsConfirmation(true); setError("Please confirm your email before signing in. A confirmation link was sent when you created the account."); } else setError(message); }
    finally { setSubmitting(false); }
  }
  async function resendConfirmation() { if (!email) { setError("Enter the email address used to create your account first."); return; } setSubmitting(true); setError(null); try { const client = await getSupabaseBrowserClient(); const { error: resendError } = await client.auth.resend({ type: "signup", email, options: { emailRedirectTo: `${window.location.origin}/login` } }); if (resendError) throw resendError; setNotice("A new confirmation link has been sent. Open it, then return here to sign in."); setNeedsConfirmation(false); } catch (caught) { setError(caught instanceof Error ? caught.message : "We could not resend your confirmation email."); } finally { setSubmitting(false); } }
  const heading = view === "signIn" ? "Welcome back" : view === "signUp" ? "Create your study space" : view === "forgot" ? "Reset your password" : "Choose a new password";
  const subheading = view === "signIn" ? "Continue with the workspace you’ve made yours." : view === "signUp" ? "Start with a secure, private workspace for your learning." : "We’ll help you get back into your account safely.";

  const primaryLabel = view === "signIn" ? "Sign in" : view === "signUp" ? "Sign up" : view === "forgot" ? "Send reset link" : "Update password";
  const formTitle = view === "signUp" ? "Sign up" : view === "signIn" ? "Welcome back" : heading;
  return <main className="relative flex min-h-screen items-center justify-center overflow-hidden bg-[#F8E7E7] px-4 py-8 text-[#724060] sm:p-8" style={{ backgroundImage: "radial-gradient(circle at 16% 8%, #FDF3F3 0, transparent 30%), radial-gradient(circle at 90% 88%, #A070A1 0, transparent 32%), linear-gradient(135deg, #FDF3F3 0%, #F8E7E7 46%, #A070A1 100%)" }}>
    <div className="pointer-events-none absolute -left-8 bottom-12 h-28 w-28 rotate-[-24deg] rounded-[42%] border-[18px] border-[#A070A1] shadow-[0_22px_36px_rgba(114,64,96,.24)]" /><div className="pointer-events-none absolute right-[9%] top-[9%] h-28 w-28 rotate-[20deg] rounded-[28px] bg-[#A070A1] shadow-[inset_-15px_-18px_24px_rgba(114,64,96,.28),20px_24px_30px_rgba(114,64,96,.24)]" /><div className="pointer-events-none absolute right-[2%] bottom-[14%] h-20 w-20 rounded-full bg-[#724060] shadow-[0_18px_35px_rgba(114,64,96,.32)]" /><div className="pointer-events-none absolute right-[13%] bottom-[4%] h-12 w-48 rotate-[32deg] rounded-full bg-[#A070A1] blur-[2px]" />
    <section className="relative z-10 grid w-full max-w-[1120px] overflow-hidden rounded-[30px] border border-[#FDF3F3] bg-[#F8E7E7]/90 shadow-[0_28px_70px_rgba(114,64,96,.25),inset_0_1px_1px_#FDF3F3] backdrop-blur-xl lg:grid-cols-[1.05fr_.95fr]">
      <div className="relative p-7 sm:p-11 lg:p-14"><div className="mb-10 flex items-center gap-2.5 text-[17px] font-bold tracking-[-.03em]"><span className="grid h-10 w-10 place-items-center overflow-hidden rounded-2xl bg-[#724060] shadow-lg shadow-[#A070A1]/30"><img src="/manus-storage/studentgpt-logo-option-1_b720cde2.png" alt="StudentGPT" className="h-8 w-8 object-contain" /></span>StudentGPT</div><div className="max-w-[430px]"><p className="text-[11px] font-bold uppercase tracking-[.19em] text-[#A070A1]">Academic studio</p><h1 className="mt-4 text-[36px] font-semibold tracking-[-.06em] sm:text-[46px]">{formTitle}</h1><p className="mt-3 text-[14px] leading-6 text-[#724060]">{subheading}</p></div>
        {authError && <p role="alert" className="mt-6 rounded-2xl border border-[#A070A1] bg-[#FDF3F3] px-4 py-3 text-sm text-[#724060]">{authError}</p>}{notice && <p role="status" className="mt-6 rounded-2xl border border-[#A070A1] bg-[#FDF3F3] px-4 py-3 text-sm text-[#724060]">{notice}</p>}{error && <p role="alert" className="mt-6 rounded-2xl border border-[#A070A1] bg-[#FDF3F3] px-4 py-3 text-sm text-[#724060]">{error}</p>}{needsConfirmation && <button type="button" disabled={submitting} onClick={resendConfirmation} className="mt-3 text-sm font-semibold text-[#724060] hover:underline">Resend confirmation email</button>}
        <form onSubmit={handleSubmit} className="mt-8 space-y-3.5">{view === "signUp" && <div><Label className="sr-only" htmlFor="fullName">Full name</Label><Input id="fullName" value={fullName} onChange={e => setFullName(e.target.value)} autoComplete="name" placeholder="Full name" className="h-12 rounded-full border-0 bg-[#FDF3F3] px-5 text-[#724060] shadow-[inset_0_1px_1px_#FDF3F3,0_5px_12px_rgba(114,64,96,.12)] placeholder:text-[#A070A1] focus-visible:ring-2 focus-visible:ring-[#724060]" required /></div>}{view !== "reset" && <div><Label className="sr-only" htmlFor="email">Email address</Label><Input id="email" type="email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="email" placeholder="Email address" className="h-12 rounded-full border-0 bg-[#FDF3F3] px-5 text-[#724060] shadow-[inset_0_1px_1px_#FDF3F3,0_5px_12px_rgba(114,64,96,.12)] placeholder:text-[#A070A1] focus-visible:ring-2 focus-visible:ring-[#724060]" required /></div>}{view !== "forgot" && <div><Label className="sr-only" htmlFor="password">{view === "reset" ? "New password" : "Password"}</Label><Input id="password" type="password" value={password} onChange={e => setPassword(e.target.value)} autoComplete={view === "reset" ? "new-password" : view === "signUp" ? "new-password" : "current-password"} placeholder={view === "reset" ? "New password" : "Password"} className="h-12 rounded-full border-0 bg-[#FDF3F3] px-5 text-[#724060] shadow-[inset_0_1px_1px_#FDF3F3,0_5px_12px_rgba(114,64,96,.12)] placeholder:text-[#A070A1] focus-visible:ring-2 focus-visible:ring-[#724060]" minLength={8} required /></div>}{view === "signUp" && <div><Label className="sr-only" htmlFor="confirmPassword">Confirm password</Label><Input id="confirmPassword" type="password" value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} autoComplete="new-password" placeholder="Confirm password" className="h-12 rounded-full border-0 bg-[#FDF3F3] px-5 text-[#724060] shadow-[inset_0_1px_1px_#FDF3F3,0_5px_12px_rgba(114,64,96,.12)] placeholder:text-[#A070A1] focus-visible:ring-2 focus-visible:ring-[#724060]" minLength={8} required /></div>}{view === "signIn" && <button type="button" onClick={() => setView("forgot")} className="ml-2 text-left text-xs font-semibold text-[#724060] hover:underline">Forgot password?</button>}<Button type="submit" disabled={submitting} className="group h-12 w-full rounded-full bg-[#724060] text-sm font-semibold text-[#FDF3F3] shadow-[0_12px_22px_rgba(114,64,96,.24)] hover:bg-[#A070A1]">{submitting ? "Please wait…" : <span className="flex items-center justify-center gap-2">{primaryLabel}<ArrowUpRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></span>}</Button></form>
        <div className="mt-6 text-center text-sm text-[#724060]">{view === "signIn" ? <>New here? <button type="button" onClick={() => setView("signUp")} className="font-bold text-[#724060] hover:underline">Create an account</button></> : <button type="button" onClick={() => { setView("signIn"); setError(null); setNotice(null); }} className="font-bold text-[#724060] hover:underline">Already have an account? Sign in</button>}</div>
      </div>
      <aside className="relative hidden overflow-hidden bg-[#A070A1] p-12 text-[#FDF3F3] lg:flex lg:flex-col lg:justify-between" style={{ backgroundImage: "radial-gradient(circle at 17% 12%, #F8E7E7 0, transparent 28%), linear-gradient(145deg, #A070A1, #724060)" }}><div className="absolute -right-10 top-14 h-36 w-36 rotate-[18deg] rounded-[34px] bg-[#F8E7E7] shadow-[inset_-20px_-18px_25px_rgba(114,64,96,.28),20px_25px_40px_rgba(114,64,96,.32)]" /><div className="absolute -left-8 bottom-12 h-24 w-24 rounded-full border-[18px] border-[#FDF3F3]" /><div className="relative max-w-[320px]"><span className="inline-flex h-10 items-center gap-2 rounded-full border border-[#FDF3F3] bg-[#A070A1] px-4 text-xs font-semibold backdrop-blur"><LockKeyhole className="h-3.5 w-3.5" /> Private study space</span><h2 className="mt-8 text-[45px] font-semibold leading-[.98] tracking-[-.06em]">Think clearly.<br />Study deeply.</h2><p className="mt-6 text-[15px] leading-6 text-[#F8E7E7]">Your notes, private documents, practice, and research stay together in one focused academic workspace.</p></div><div className="relative flex items-center justify-between border-t border-[#FDF3F3] pt-5 text-[11px] font-medium text-[#F8E7E7]"><span>Structured learning</span><span>Built for exams</span></div></aside>
    </section>
  </main>;
}
