import { AppLoading, AuthError, StudentAppShell } from "@/components/StudentAppShell";
import { PracticeHistory } from "@/components/PracticeHistory";
import { useSupabaseAuth } from "@/contexts/SupabaseAuthContext";
import { trpc } from "@/lib/trpc";
import { BrainCircuit, ChevronLeft, ChevronRight, Eye, Layers3, RotateCcw, Sparkles } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { useLocation } from "wouter";

export default function Practice() {
  const { user, loading, authError } = useSupabaseAuth(); const [, setLocation] = useLocation(); const utils = trpc.useUtils();
  const [tab, setTab] = useState<"quiz" | "flashcards">("quiz"); const [topic, setTopic] = useState(""); const [subjectId, setSubjectId] = useState(""); const [documentId, setDocumentId] = useState(""); const [scopeType, setScopeType] = useState<"topic" | "chapter" | "section" | "range" | "document">("topic"); const [scopeLabel, setScopeLabel] = useState(""); const [questionCount, setQuestionCount] = useState("5"); const [difficulty, setDifficulty] = useState<"easy" | "medium" | "hard">("medium"); const [quiz, setQuiz] = useState<Awaited<ReturnType<typeof generatePlaceholder>> | null>(null); const [answers, setAnswers] = useState<Record<number, string>>({}); const [result, setResult] = useState<{ score: number; totalQuestions: number } | null>(null); const [cardIndex, setCardIndex] = useState(0); const [revealed, setRevealed] = useState(false); const [error, setError] = useState<string | null>(null);
  const cards = trpc.flashcards.list.useQuery(undefined, { enabled: Boolean(user) });
  const subjects = trpc.academic.listSubjects.useQuery(undefined, { enabled: Boolean(user) });
  const documents = trpc.documents.list.useQuery(undefined, { enabled: Boolean(user) });
  const generateQuiz = trpc.quizzes.generate.useMutation({ onError: caught => setError(caught.message) });
  const submitQuiz = trpc.quizzes.submit.useMutation({ onSuccess: data => setResult({ score: data.score, totalQuestions: data.totalQuestions }), onError: caught => setError(caught.message) });
  const generateCards = trpc.flashcards.generate.useMutation({ onSuccess: () => { utils.flashcards.list.invalidate(); setCardIndex(0); setRevealed(false); }, onError: caught => setError(caught.message) });
  const review = trpc.flashcards.review.useMutation({ onSuccess: () => { setCardIndex(index => Math.min(index + 1, Math.max(0, (cards.data?.length ?? 1) - 1))); setRevealed(false); } });
  useEffect(() => { if (!loading && !authError && !user) setLocation("/login"); }, [authError, loading, setLocation, user]);
  if (loading) return <AppLoading />; if (authError) return <AuthError message={authError} />; if (!user) return <AppLoading />;
  async function createQuiz(event: FormEvent) { event.preventDefault(); setError(null); setResult(null); const scope = scopeLabel.trim() || topic.trim(); try { const generated = await generateQuiz.mutateAsync({ title: `${scope} practice`, topic, subjectId: subjectId ? Number(subjectId) : null, documentId: documentId ? Number(documentId) : null, scopeType, scopeLabel: scope, questionCount: Math.max(3, Math.min(15, Number(questionCount) || 5)), difficulty }); setQuiz(generated as unknown as Awaited<ReturnType<typeof generatePlaceholder>>); setAnswers({}); } catch {} }
  async function createCards(event: FormEvent) { event.preventDefault(); setError(null); const scope = scopeLabel.trim() || topic.trim(); try { await generateCards.mutateAsync({ topic, subjectId: subjectId ? Number(subjectId) : null, documentId: documentId ? Number(documentId) : null, scopeType, scopeLabel: scope }); } catch {} }
  function submitAnswers() { if (!quiz) return; submitQuiz.mutate({ quizId: quiz.quiz.id, answers: Object.entries(answers).map(([questionId, answer]) => ({ questionId: Number(questionId), answer })) }); }
  const activeCard = cards.data?.[cardIndex];
  return <StudentAppShell><div className="mx-auto max-w-[1100px] p-5 sm:p-8 lg:p-10"><header><p className="text-[13px] font-medium text-[#724060]">Academic workspace</p><h1 className="mt-1 text-[30px] font-semibold tracking-[-.045em]">Practice studio</h1><p className="mt-2 text-sm text-[#724060]">Generate active-recall exercises from a topic you are actually studying.</p></header><div className="mt-7 flex gap-2 border-b border-black/[.08]"><button onClick={() => setTab("quiz")} className={`border-b-2 px-3 py-3 text-[13px] font-medium ${tab === "quiz" ? "border-[#A070A1] text-[#A070A1]" : "border-transparent text-[#724060]"}`}>Quiz</button><button onClick={() => setTab("flashcards")} className={`border-b-2 px-3 py-3 text-[13px] font-medium ${tab === "flashcards" ? "border-[#A070A1] text-[#A070A1]" : "border-transparent text-[#724060]"}`}>Flashcards</button></div>{error && <p role="alert" className="mt-5 rounded-xl bg-[#F8E7E7] p-3 text-[13px] text-[#A070A1]">{error}</p>}<PracticeHistory />
    <section className="mt-6 rounded-2xl border border-[#A070A1] bg-[#FDF3F3] p-5 sm:p-6"><form onSubmit={tab === "quiz" ? createQuiz : createCards}><div className="grid gap-3 lg:grid-cols-[1.2fr_.85fr_.9fr_.7fr_.85fr]"> <input value={topic} onChange={event => setTopic(event.target.value)} placeholder="Topic or subject you want to practise" className="h-11 min-w-0 rounded-xl border border-black/[.11] px-3 text-sm outline-none focus:border-[#A070A1]" required /><select value={subjectId} onChange={event => setSubjectId(event.target.value)} className="h-11 rounded-xl border border-black/[.11] bg-[#FDF3F3] px-3 text-[12px]"><option value="">No subject selected</option>{subjects.data?.map(subject => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select><select value={documentId} onChange={event => setDocumentId(event.target.value)} className="h-11 rounded-xl border border-black/[.11] bg-[#FDF3F3] px-3 text-[12px]"><option value="">Topic only</option>{documents.data?.map(document => <option key={document.id} value={document.id}>{document.originalName}</option>)}</select><select value={scopeType} onChange={event => setScopeType(event.target.value as typeof scopeType)} className="h-11 rounded-xl border border-black/[.11] bg-[#FDF3F3] px-3 text-[12px]"><option value="topic">Topic</option><option value="chapter">Chapter</option><option value="section">Section</option><option value="range">Range</option><option value="document">Complete book</option></select><input value={scopeLabel} onChange={event => setScopeLabel(event.target.value)} placeholder={scopeType === "chapter" ? "e.g. Chapter 6" : scopeType === "document" ? "Whole book" : "Exact scope"} className="h-11 min-w-0 rounded-xl border border-black/[.11] px-3 text-sm outline-none focus:border-[#A070A1]" /></div><div className="mt-3 flex flex-wrap gap-3">{tab === "quiz" && <><label className="flex h-10 items-center gap-2 rounded-xl border border-black/[.08] px-3 text-[12px] text-[#724060]">MCQs <input type="number" min="3" max="15" value={questionCount} onChange={event => setQuestionCount(event.target.value)} className="w-12 bg-transparent text-center outline-none" /></label><select value={difficulty} onChange={event => setDifficulty(event.target.value as typeof difficulty)} className="h-10 rounded-xl border border-black/[.11] bg-[#FDF3F3] px-3 text-[12px]"><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></>}<button disabled={generateQuiz.isPending || generateCards.isPending} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[#724060] px-4 text-[13px] font-medium text-[#FDF3F3] hover:bg-[#724060]">{tab === "quiz" ? <BrainCircuit className="h-4 w-4" /> : <Layers3 className="h-4 w-4" />}{generateQuiz.isPending || generateCards.isPending ? "Generating…" : tab === "quiz" ? "Generate scoped quiz" : "Generate scoped cards"}</button></div></form></section>
    {tab === "quiz" && <section className="mt-5">{quiz ? <div className="rounded-2xl border border-[#A070A1] bg-[#FDF3F3] p-5 sm:p-7"><div className="flex items-start justify-between"><div><h2 className="text-[18px] font-semibold">{quiz.quiz.title}</h2><p className="mt-1 text-[12px] text-[#724060]">{quiz.questions.length} questions · {quiz.quiz.difficulty} difficulty</p></div>{result && <span className="rounded-xl bg-[#F8E7E7] px-3 py-2 text-[13px] font-semibold text-[#A070A1]">{result.score}/{result.totalQuestions}</span>}</div><div className="mt-7 space-y-7">{quiz.questions.map((question, index) => <div key={question.id}><p className="text-[14px] font-medium"><span className="mr-2 text-[#A070A1]">{index + 1}.</span>{question.prompt}</p><div className="mt-3 grid gap-2">{(question.options as string[]).map(option => <label key={option} className={`flex cursor-pointer items-center gap-3 rounded-xl border px-3 py-3 text-[13px] ${answers[question.id] === option ? "border-[#A070A1] bg-[#F8E7E7]" : "border-black/[.08] hover:bg-[#F8E7E7]"}`}><input type="radio" name={`question-${question.id}`} checked={answers[question.id] === option} onChange={() => setAnswers({ ...answers, [question.id]: option })} className="accent-[#A070A1]" />{option}</label>)}</div>{result && <p className="mt-3 rounded-xl bg-[#F8E7E7] p-3 text-[12px] leading-5 text-[#724060]"><b>Answer:</b> {question.correctAnswer}<br /><b>Why:</b> {question.explanation}</p>}</div>)}</div><button onClick={submitAnswers} disabled={submitQuiz.isPending || Object.keys(answers).length !== quiz.questions.length} className="mt-7 h-10 rounded-xl bg-[#A070A1] px-4 text-[13px] font-medium text-[#FDF3F3] disabled:opacity-50">{submitQuiz.isPending ? "Scoring…" : "Score quiz"}</button></div> : <div className="rounded-2xl border border-dashed border-[#A070A1] bg-[#FDF3F3] px-6 py-16 text-center"><BrainCircuit className="mx-auto h-6 w-6 text-[#A070A1]" /><h2 className="mt-4 text-[17px] font-semibold">Active recall, made focused</h2><p className="mx-auto mt-2 max-w-sm text-[13px] leading-5 text-[#724060]">Enter a real topic and StudentGPT will create a stored, scorable five-question quiz.</p></div>}</section>}
    {tab === "flashcards" && <section className="mt-5">{cards.isLoading ? <div className="rounded-2xl bg-[#FDF3F3] p-8 text-sm text-[#724060]">Loading flashcards…</div> : activeCard ? <div className="rounded-2xl border border-[#A070A1] bg-[#FDF3F3] p-5 sm:p-7"><div className="flex items-center justify-between text-[12px] text-[#724060]"><span>Card {cardIndex + 1} of {cards.data?.length}</span><span>Stored review set</span></div><button onClick={() => setRevealed(!revealed)} className="mt-5 flex min-h-[260px] w-full flex-col items-center justify-center rounded-2xl bg-[#F8E7E7] p-8 text-center transition hover:bg-[#F8E7E7]"><p className="max-w-xl text-[20px] font-semibold tracking-[-.025em]">{revealed ? activeCard.back : activeCard.front}</p><span className="mt-5 inline-flex items-center gap-1 text-[12px] text-[#A070A1]"><Eye className="h-3.5 w-3.5" />{revealed ? "Hide answer" : "Reveal answer"}</span></button>{revealed && <div className="mt-5 grid grid-cols-4 gap-2">{(["again", "hard", "good", "easy"] as const).map(outcome => <button key={outcome} onClick={() => review.mutate({ flashcardId: activeCard.id, outcome })} className="h-10 rounded-xl border border-black/[.08] text-[12px] font-medium capitalize hover:bg-[#F8E7E7]">{outcome}</button>)}</div>}<div className="mt-5 flex justify-between"><button onClick={() => { setCardIndex(Math.max(0, cardIndex - 1)); setRevealed(false); }} disabled={cardIndex === 0} className="inline-flex items-center gap-1 text-[12px] font-medium text-[#724060] disabled:opacity-40"><ChevronLeft className="h-4 w-4" />Previous</button><button onClick={() => { setCardIndex(Math.min((cards.data?.length ?? 1) - 1, cardIndex + 1)); setRevealed(false); }} disabled={cardIndex >= (cards.data?.length ?? 1) - 1} className="inline-flex items-center gap-1 text-[12px] font-medium text-[#A070A1] disabled:opacity-40">Next<ChevronRight className="h-4 w-4" /></button></div></div> : <div className="rounded-2xl border border-dashed border-[#A070A1] bg-[#FDF3F3] px-6 py-16 text-center"><Layers3 className="mx-auto h-6 w-6 text-[#A070A1]" /><h2 className="mt-4 text-[17px] font-semibold">Build a focused review set</h2><p className="mx-auto mt-2 max-w-sm text-[13px] leading-5 text-[#724060]">Generate eight actual flashcards from a topic, then reveal and record each review outcome.</p></div>}</section>}
  </div></StudentAppShell>;
}

async function generatePlaceholder() { return { quiz: { id: 0, title: "", difficulty: "medium" }, questions: [] as Array<{ id: number; prompt: string; options: string[]; correctAnswer: string; explanation: string }> }; }
