import { AppLoading, AuthError, StudentAppShell } from "@/components/StudentAppShell";
import { useSupabaseAuth } from "@/contexts/SupabaseAuthContext";
import { getSupabaseAccessToken } from "@/lib/supabase";
import { trpc } from "@/lib/trpc";
import { toPng } from "html-to-image";
import { BookOpenCheck, Compass, Download, FileText, Lightbulb, ListChecks, MessageCircleMore, Network, PlayCircle, Plus, SearchCheck, Sparkles, Target, Wand2 } from "lucide-react";
import { FormEvent, ReactNode, useEffect, useMemo, useRef, useState } from "react";
import { useLocation } from "wouter";

type Concept = { name: string; explanation: string };
type Board = { projectFocus?: string; objectives?: string[]; methodology?: string[]; applications?: string[]; misconceptions?: string[]; verificationChecklist?: string[] };
function strings(value: unknown) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function concepts(value: unknown) { return Array.isArray(value) ? value.filter((item): item is Concept => Boolean(item && typeof item === "object" && typeof (item as Concept).name === "string" && typeof (item as Concept).explanation === "string")) : []; }
function board(value: unknown): Board { return value && typeof value === "object" ? value as Board : {}; }
function BoardCell({ title, icon, tone, children, className = "" }: { title: string; icon: ReactNode; tone: string; children: ReactNode; className?: string }) { return <section className={`relative h-fit self-start overflow-hidden rounded-[10px] border border-[#F8E7E7] bg-[#FDF3F3] p-4 shadow-[0_2px_8px_rgba(35,48,52,.06)] sm:p-5 ${className}`}><div className={`absolute right-0 top-0 h-1 w-24 ${tone}`} /><div className="flex items-center gap-2"><span className={`grid h-8 w-8 place-items-center rounded-md ${tone} text-[#724060] shadow-sm`}>{icon}</span><h3 className="text-[14px] font-bold tracking-[-.02em] text-[#724060]">{title}</h3></div><div className="mt-4 text-[12px] leading-5 text-[#724060]">{children}</div></section>; }

export default function Research() {
  const { user, loading, authError } = useSupabaseAuth(); const [, setLocation] = useLocation(); const utils = trpc.useUtils();
  const briefs = trpc.research.list.useQuery(undefined, { enabled: Boolean(user) }); const subjects = trpc.academic.listSubjects.useQuery(undefined, { enabled: Boolean(user) });
  const [selectedId, setSelectedId] = useState<number | null>(null); const selected = trpc.research.get.useQuery({ briefId: selectedId ?? 0 }, { enabled: Boolean(selectedId) });
  const [composerOpen, setComposerOpen] = useState(false); const [topic, setTopic] = useState(""); const [subjectId, setSubjectId] = useState(""); const [sourceTitle, setSourceTitle] = useState(""); const [sourceUrl, setSourceUrl] = useState(""); const [sourceNote, setSourceNote] = useState(""); const [error, setError] = useState<string | null>(null); const [exportingCanvas, setExportingCanvas] = useState(false); const canvasRef = useRef<HTMLDivElement>(null);
  const createFromTopic = trpc.research.createFromTopic.useMutation(); const synthesize = trpc.research.synthesize.useMutation(); const addSource = trpc.research.addSource.useMutation(); const exportDocument = trpc.research.exportDocument.useMutation();
  useEffect(() => { if (!loading && !authError && !user) setLocation("/login"); }, [authError, loading, setLocation, user]);
  useEffect(() => { if (!selectedId && briefs.data?.[0]) setSelectedId(briefs.data[0].id); }, [briefs.data, selectedId]);
  const brief = selected.data?.brief; const videos = trpc.research.videos.useQuery({ query: brief?.title || "study topic" }, { enabled: Boolean(brief) }); const community = trpc.research.community.useQuery({ query: brief?.title || "study topic" }, { enabled: Boolean(brief) }); const exportHistory = trpc.research.exports.useQuery({ briefId: selectedId ?? 0 }, { enabled: Boolean(selectedId) });
  const sourceItems = selected.data?.sources ?? []; const keyConcepts = useMemo(() => concepts(brief?.keyConcepts), [brief?.keyConcepts]); const studyQuestions = useMemo(() => strings(brief?.studyQuestions), [brief?.studyQuestions]); const actionPlan = useMemo(() => strings(brief?.actionPlan), [brief?.actionPlan]); const projectBoard = useMemo(() => board(brief?.boardContent), [brief?.boardContent]);
  if (loading) return <AppLoading />; if (authError) return <AuthError message={authError} />; if (!user) return <AppLoading />;
  async function createBrief(event: FormEvent) { event.preventDefault(); setError(null); try { const created = await createFromTopic.mutateAsync({ topic, subjectId: subjectId ? Number(subjectId) : null }); setSelectedId(created.brief.id); await synthesize.mutateAsync({ briefId: created.brief.id }); await Promise.all([utils.research.list.invalidate(), utils.research.get.invalidate({ briefId: created.brief.id })]); setComposerOpen(false); setTopic(""); setSubjectId(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not build this research canvas."); } }
  async function runSynthesis() { if (!selectedId) return; setError(null); try { await synthesize.mutateAsync({ briefId: selectedId }); await Promise.all([utils.research.list.invalidate(), utils.research.get.invalidate({ briefId: selectedId })]); } catch (caught) { setError(caught instanceof Error ? caught.message : "The research synthesis could not be created."); } }
  async function saveSource(event: FormEvent) { event.preventDefault(); if (!selectedId) return; setError(null); try { await addSource.mutateAsync({ briefId: selectedId, title: sourceTitle, url: sourceUrl || null, note: sourceNote || null }); await utils.research.get.invalidate({ briefId: selectedId }); setSourceTitle(""); setSourceUrl(""); setSourceNote(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not save this source note."); } }
  async function downloadToDevice(exportId: number, fileName: string) { const token = getSupabaseAccessToken(); if (!token) throw new Error("Your session is no longer active. Please sign in again."); const response = await fetch(`/api/research-exports/${exportId}/download`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error("The saved research paper could not be downloaded."); const objectUrl = URL.createObjectURL(await response.blob()); const link = document.createElement("a"); link.href = objectUrl; link.download = fileName; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(objectUrl); }
  async function saveResearchDocument() { if (!selectedId) return; setError(null); try { const saved = await exportDocument.mutateAsync({ briefId: selectedId }); await utils.research.exports.invalidate({ briefId: selectedId }); await downloadToDevice(saved.export.id, saved.export.fileName); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not save this research paper."); } }
  async function downloadSavedExport(exportId: number, fileName: string) { setError(null); try { await downloadToDevice(exportId, fileName); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not download this research paper."); } }
  async function downloadCanvasImage() { if (!canvasRef.current || !brief) return; setError(null); setExportingCanvas(true); try { const dataUrl = await toPng(canvasRef.current, { cacheBust: true, backgroundColor: "#F8E7E7", pixelRatio: 2 }); const link = document.createElement("a"); link.href = dataUrl; link.download = `${brief.title.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase() || "research-project"}-canvas.png`; document.body.appendChild(link); link.click(); link.remove(); } catch { setError("The canvas image could not be created. Please try again."); } finally { setExportingCanvas(false); } }
  const miniList = (items: string[], tone = "bg-[#F8E7E7]") => items.length ? <ul className="space-y-2">{items.map((item, index) => <li key={`${item}-${index}`} className="flex gap-2"><span className={`mt-0.5 h-4 w-4 shrink-0 rotate-3 ${tone} shadow-sm`} /><span>{item}</span></li>)}</ul> : <p className="text-[#A070A1]">Refresh the research board to generate this section.</p>;

  return <StudentAppShell><div className="min-h-screen bg-[#F8E7E7] px-4 py-5 sm:px-7 sm:py-8 lg:px-10"><div className="mx-auto max-w-[1500px]">
    <header className="relative overflow-hidden border border-[#A070A1] bg-[#724060] px-6 py-6 text-[#FDF3F3] shadow-[0_15px_42px_rgba(114,64,96,.18)] sm:px-8"><div className="absolute inset-0 opacity-15" style={{ backgroundImage: "linear-gradient(90deg, transparent 49.5%, #FDF3F3 50%, transparent 50.5%), linear-gradient(transparent 49.5%, #FDF3F3 50%, transparent 50.5%)", backgroundSize: "40px 40px" }} /><div className="relative flex flex-wrap items-end justify-between gap-5"><div><p className="inline-flex items-center gap-2 bg-[#F8E7E7] px-3 py-1 text-[10px] font-bold uppercase tracking-[.16em] text-[#724060]"><Compass className="h-3.5 w-3.5" /> Research project canvas</p><h1 className="mt-4 max-w-3xl text-[30px] font-bold leading-[1.04] tracking-[-.05em] sm:text-[42px]">Build a deeper, clearer understanding of any topic.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#F8E7E7]">Turn a topic into a visual project board: purpose, concepts, methods, evidence to seek, questions, a study timeline, and carefully ranked public resources.</p></div><button onClick={() => setComposerOpen(true)} className="inline-flex h-11 items-center gap-2 bg-[#F8E7E7] px-4 text-[13px] font-bold text-[#724060] shadow-sm transition hover:bg-[#FDF3F3]"><Plus className="h-4 w-4" /> Start a project</button></div></header>
    {error && <p role="alert" className="mt-5 border border-[#F8E7E7] bg-[#F8E7E7] px-4 py-3 text-sm text-[#724060]">{error}</p>}
    <div className="mt-6 space-y-6"><aside className="border border-[#F8E7E7] bg-[#FDF3F3] p-3 shadow-sm"><div className="flex items-center justify-between border-b border-[#F8E7E7] px-2 pb-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#A070A1]">Project library</p><p className="mt-1 text-[12px] text-[#A070A1]">Private research boards</p></div><span className="bg-[#F8E7E7] px-2 py-1 text-[11px] font-bold text-[#724060]">{briefs.data?.length ?? 0}</span></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{briefs.data?.length ? briefs.data.map(item => <button key={item.id} onClick={() => setSelectedId(item.id)} className={`min-w-[220px] border-l-4 px-3 py-3 text-left transition ${item.id === selectedId ? "border-[#A070A1] bg-[#FDF3F3]" : "border-transparent hover:bg-[#F8E7E7]"}`}><p className="line-clamp-2 text-[13px] font-bold text-[#724060]">{item.title}</p><p className="mt-1 line-clamp-2 text-[11px] leading-4 text-[#A070A1]">{item.researchQuestion}</p></button>) : <p className="p-4 text-center text-[12px] leading-5 text-[#A070A1]">Your saved topic boards will appear here.</p>}</div></aside>
      <main className="min-w-0">{brief ? <><div className="border border-[#F8E7E7] bg-[#FDF3F3] p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#A070A1]">{brief.status === "ready" ? "Canvas ready" : "Canvas in progress"}</p><h2 className="mt-2 text-[28px] font-bold tracking-[-.045em] text-[#724060] sm:text-[36px]">{brief.title}</h2><p className="mt-3 max-w-3xl text-[14px] leading-6 text-[#724060]">{brief.researchQuestion}</p></div><div className="flex flex-wrap gap-2"><button onClick={runSynthesis} disabled={synthesize.isPending || brief.status === "generating"} className="inline-flex h-10 items-center gap-2 bg-[#724060] px-3 text-[12px] font-bold text-[#FDF3F3] disabled:opacity-60"><Wand2 className="h-4 w-4" />{synthesize.isPending ? "Building…" : "Deepen canvas"}</button><button onClick={downloadCanvasImage} disabled={exportingCanvas || brief.status !== "ready"} className="inline-flex h-10 items-center gap-2 bg-[#F8E7E7] px-3 text-[12px] font-bold text-[#724060] disabled:opacity-60"><Download className="h-4 w-4" />{exportingCanvas ? "Capturing canvas…" : "Download canvas image"}</button><button onClick={saveResearchDocument} disabled={exportDocument.isPending} className="inline-flex h-10 items-center gap-2 bg-[#F8E7E7] px-3 text-[12px] font-bold text-[#724060] disabled:opacity-60"><FileText className="h-4 w-4" />{exportDocument.isPending ? "Preparing…" : "Download research paper"}</button></div></div>{brief.failureReason && <p className="mt-4 border-l-4 border-[#A070A1] bg-[#FDF3F3] p-3 text-[13px] text-[#724060]">{brief.failureReason}</p>}</div>
        {brief.status === "ready" ? <div ref={canvasRef} className="mt-6 overflow-hidden rounded-[12px] border border-[#F8E7E7] bg-[#FDF3F3] p-2 shadow-[0_18px_45px_rgba(35,48,52,.09)]"><div className="flex flex-wrap items-center justify-between gap-3 rounded-[8px] border border-[#A070A1] bg-[#FDF3F3] px-4 py-3"><div className="flex items-center gap-2"><Network className="h-4 w-4 text-[#724060]" /><h2 className="text-[15px] font-bold text-[#724060]">Research Project Canvas</h2></div><span className="text-[10px] font-bold uppercase tracking-[.14em] text-[#A070A1]">StudentGPT study board · v1</span></div><div className="mt-2 space-y-2">
          <BoardCell title="Problem, objectives & questions" icon={<SearchCheck className="h-4 w-4" />} tone="bg-[#F8E7E7]"><div className="grid items-start gap-5 lg:grid-cols-[.9fr_1.1fr_1.4fr]"><p className="whitespace-pre-wrap leading-5">{projectBoard.projectFocus || brief.overview}</p><div><p className="mb-2 text-[10px] font-bold uppercase tracking-[.12em] text-[#A070A1]">Objectives</p>{miniList(strings(projectBoard.objectives), "bg-[#F8E7E7]")}</div><div><p className="mb-2 text-[10px] font-bold uppercase tracking-[.12em] text-[#A070A1]">Questions to investigate</p><ol className="space-y-2">{studyQuestions.map((question, index) => <li key={`${question}-${index}`} className="flex gap-2"><span className="font-bold text-[#724060]">{index + 1}.</span>{question}</li>)}</ol></div></div></BoardCell>
          <BoardCell title="Key concepts" icon={<Network className="h-4 w-4" />} tone="bg-[#F8E7E7]"><div className="grid gap-x-5 gap-y-4 sm:grid-cols-2 xl:grid-cols-3">{keyConcepts.map((concept, index) => <div key={`${concept.name}-${index}`} className="border-l-2 border-[#F8E7E7] pl-3"><p className="font-bold text-[#724060]">{concept.name}</p><p className="mt-0.5">{concept.explanation}</p></div>)}</div></BoardCell>
          <BoardCell title="Method, impact & study sequence" icon={<ListChecks className="h-4 w-4" />} tone="bg-[#F8E7E7]"><div className="grid items-start gap-5 lg:grid-cols-3"><div><p className="mb-2 text-[10px] font-bold uppercase tracking-[.12em] text-[#A070A1]">Methodology</p>{miniList(strings(projectBoard.methodology), "bg-[#F8E7E7]")}</div><div><p className="mb-2 text-[10px] font-bold uppercase tracking-[.12em] text-[#A070A1]">Applications & impact</p>{miniList(strings(projectBoard.applications), "bg-[#F8E7E7]")}</div><div><p className="mb-2 text-[10px] font-bold uppercase tracking-[.12em] text-[#A070A1]">Study timeline</p>{miniList(actionPlan, "bg-[#F8E7E7]")}</div></div></BoardCell>
          <BoardCell title="Misconceptions to avoid" icon={<Lightbulb className="h-4 w-4" />} tone="bg-[#F8E7E7]">{miniList(strings(projectBoard.misconceptions), "bg-[#F8E7E7]")}</BoardCell>
          <BoardCell title="Resources & verification" icon={<PlayCircle className="h-4 w-4" />} tone="bg-[#F8E7E7]"><p className="mb-3 font-semibold text-[#724060]">Suggested videos are ranked against the exact topic title.</p><div className="grid gap-2 md:grid-cols-3">{videos.data?.slice(0, 3).map(video => <a key={video.id} href={video.url} target="_blank" rel="noreferrer" className="block border-l-2 border-[#A070A1] bg-[#FDF3F3] p-2 hover:bg-[#FDF3F3]"><p className="line-clamp-2 font-bold text-[#724060]">{video.title}</p><p className="mt-1 text-[10px] text-[#A070A1]">{video.channelTitle} · {video.relevance}</p></a>)}</div><div className="mt-3 border-t border-[#F8E7E7] pt-2"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#A070A1]">Check before relying</p>{miniList(strings(projectBoard.verificationChecklist), "bg-[#F8E7E7]")}</div></BoardCell>
        </div></div> : <div className="mt-6 border border-dashed border-[#F8E7E7] bg-[#FDF3F3] p-10 text-center text-sm text-[#A070A1]">StudentGPT is preparing the project canvas.</div>}
        <section className="mt-6 border border-[#F8E7E7] bg-[#FDF3F3] p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="flex items-center gap-2"><PlayCircle className="h-4 w-4 text-[#A070A1]" /><h3 className="text-[15px] font-bold text-[#724060]">Topic-matched YouTube resources</h3></div><p className="mt-1 text-[12px] leading-5 text-[#A070A1]">Videos are searched using the exact topic title and ranked by title and description relevance.</p></div><span className="bg-[#F8E7E7] px-2 py-1 text-[10px] font-bold uppercase tracking-[.12em] text-[#A070A1]">YouTube</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{videos.isLoading ? [1, 2, 3].map(item => <div key={item} className="h-44 animate-pulse bg-[#F8E7E7]" />) : videos.data?.length ? videos.data.map(video => <a key={video.id} href={video.url} target="_blank" rel="noreferrer" className="group overflow-hidden border border-[#F8E7E7] bg-[#FDF3F3] transition hover:-translate-y-0.5 hover:shadow-md">{video.thumbnailUrl && <img src={video.thumbnailUrl} alt="" className="h-28 w-full object-cover" />}<div className="p-3"><p className="line-clamp-2 text-[13px] font-bold leading-5 text-[#724060]">{video.title}</p><p className="mt-1 truncate text-[11px] text-[#A070A1]">{video.channelTitle}</p><p className="mt-3 text-[10px] font-bold uppercase tracking-[.1em] text-[#A070A1]">{video.relevance} · Watch video</p></div></a>) : <p className="border border-dashed border-[#F8E7E7] p-4 text-[12px] text-[#A070A1]">No topic-matched YouTube videos were returned. Try refreshing the canvas with a more specific title.</p>}</div></section>
        <div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="border border-[#F8E7E7] bg-[#FDF3F3] p-5"><div className="flex items-center gap-2"><MessageCircleMore className="h-4 w-4 text-[#A070A1]" /><h3 className="text-[14px] font-bold">Community perspectives</h3></div><p className="mt-1 text-[12px] leading-5 text-[#A070A1]">Public Reddit and Quora links are contextual perspectives, not verified academic evidence.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{community.data?.slice(0, 4).map(item => <a key={item.url} href={item.url} target="_blank" rel="noreferrer" className="border border-[#F8E7E7] bg-[#FDF3F3] p-3 hover:bg-[#FDF3F3]"><span className="text-[10px] font-bold uppercase tracking-[.12em] text-[#A070A1]">{item.source}</span><p className="mt-2 line-clamp-2 text-[12px] font-bold leading-5 text-[#724060]">{item.title}</p></a>)}</div></section><section className="border border-[#F8E7E7] bg-[#FDF3F3] p-5"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-[#A070A1]" /><h3 className="text-[14px] font-bold">Saved research papers</h3></div><p className="mt-1 text-[12px] leading-5 text-[#A070A1]">Download a Markdown research paper directly to this device.</p><div className="mt-4 space-y-2">{exportHistory.data?.length ? exportHistory.data.map(item => <button key={item.id} onClick={() => downloadSavedExport(item.id, item.fileName)} className="flex w-full items-center justify-between gap-3 border border-[#F8E7E7] bg-[#FDF3F3] px-3 py-2 text-left hover:bg-[#FDF3F3]"><span className="truncate text-[12px] font-bold text-[#724060]">{item.fileName}</span><Download className="h-3.5 w-3.5 shrink-0 text-[#A070A1]" /></button>) : <p className="rounded-xl bg-[#FDF3F3] p-3 text-[12px] text-[#A070A1]">Use Download research paper to create the first local file.</p>}</div></section></div>
        <section className="mt-6 border border-[#F8E7E7] bg-[#FDF3F3] p-5"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-[#A070A1]" /><h3 className="text-[14px] font-bold">Source desk</h3></div><p className="mt-1 text-[12px] text-[#A070A1]">Add your own sources or teacher notes, then deepen the canvas again.</p><div className="mt-4 grid gap-5 lg:grid-cols-[1fr_.9fr]"><div className="space-y-2">{sourceItems.length ? sourceItems.map(source => <div key={source.id} className="border border-[#F8E7E7] bg-[#FDF3F3] p-3"><p className="text-[12px] font-bold">{source.title}</p>{source.url && <a href={source.url} target="_blank" rel="noreferrer" className="mt-1 block truncate text-[11px] text-[#A070A1] hover:underline">{source.url}</a>}{source.note && <p className="mt-2 text-[12px] leading-5 text-[#A070A1]">{source.note}</p>}</div>) : <p className="border border-dashed border-[#F8E7E7] p-4 text-[12px] text-[#A070A1]">No source notes saved yet.</p>}</div><form onSubmit={saveSource} className="border border-[#F8E7E7] bg-[#FDF3F3] p-4"><p className="text-[12px] font-bold">Add source note</p><input required value={sourceTitle} onChange={event => setSourceTitle(event.target.value)} placeholder="Source title" className="mt-3 h-10 w-full border border-[#F8E7E7] px-3 text-[12px] outline-none focus:border-[#A070A1]" /><input value={sourceUrl} onChange={event => setSourceUrl(event.target.value)} placeholder="Optional URL" type="url" className="mt-2 h-10 w-full border border-[#F8E7E7] px-3 text-[12px] outline-none focus:border-[#A070A1]" /><textarea value={sourceNote} onChange={event => setSourceNote(event.target.value)} placeholder="Key evidence or notes" className="mt-2 min-h-20 w-full border border-[#F8E7E7] p-3 text-[12px] outline-none focus:border-[#A070A1]" /><button disabled={addSource.isPending} className="mt-3 h-9 bg-[#724060] px-3 text-[12px] font-bold text-[#FDF3F3]">Save source</button></form></div></section>
      </> : <div className="grid min-h-[540px] place-items-center border border-dashed border-[#F8E7E7] bg-[#FDF3F3] p-8 text-center"><div><Sparkles className="mx-auto h-7 w-7 text-[#A070A1]" /><h2 className="mt-4 text-xl font-bold">Start a deeper research board.</h2><p className="mx-auto mt-2 max-w-sm text-[13px] leading-6 text-[#A070A1]">Choose a topic and StudentGPT will create the structured canvas, ranked video resources, community links, and a downloadable paper.</p><button onClick={() => setComposerOpen(true)} className="mt-5 bg-[#F8E7E7] px-4 py-2 text-[12px] font-bold text-[#724060]">Start a project</button></div></div>}</main></div>
    {composerOpen && <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-[#724060]/40 p-4 backdrop-blur-sm"><form onSubmit={createBrief} className="w-full max-w-xl border border-[#F8E7E7] bg-[#FDF3F3] p-6 shadow-[0_24px_80px_rgba(10,20,30,.3)]"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#A070A1]">New research project</p><h2 className="mt-2 text-[25px] font-bold tracking-[-.04em] text-[#724060]">What would you like to understand?</h2><p className="mt-2 text-[13px] leading-5 text-[#A070A1]">StudentGPT will build a detailed project board rather than a short summary.</p><div className="mt-6 space-y-4"><label className="block text-[12px] font-bold text-[#724060]">Topic<input required minLength={3} value={topic} onChange={event => setTopic(event.target.value)} placeholder="For example: Computer networks" className="mt-1.5 h-11 w-full border border-[#F8E7E7] bg-[#FDF3F3] px-3 text-sm outline-none focus:border-[#A070A1]" /></label><label className="block text-[12px] font-bold text-[#724060]">Connect to a subject <span className="font-normal text-[#A070A1]">optional</span><select value={subjectId} onChange={event => setSubjectId(event.target.value)} className="mt-1.5 h-11 w-full border border-[#F8E7E7] bg-[#FDF3F3] px-3 text-sm outline-none focus:border-[#A070A1]"><option value="">No subject selected</option>{subjects.data?.map(subject => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setComposerOpen(false)} className="h-10 px-4 text-[13px] font-bold text-[#A070A1]">Cancel</button><button disabled={createFromTopic.isPending || synthesize.isPending} className="h-10 bg-[#724060] px-4 text-[13px] font-bold text-[#FDF3F3] disabled:opacity-60">{createFromTopic.isPending || synthesize.isPending ? "Building board…" : "Build project canvas"}</button></div></form></div>}
  </div></div></StudentAppShell>;
}
